blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/welcomemanish/aruba-cpcr/discussions
    about: For general questions, please use GitHub Discussions rather than opening an issue.
